# Generated by Django 5.1.3 on 2024-12-05 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('position', models.CharField(max_length=255, verbose_name='职位')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='底薪')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='提成')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submitted', to='tianshu.employee', verbose_name='提交人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('customer_group', models.CharField(max_length=255, verbose_name='客户群')),
                ('contact_person', models.CharField(max_length=255, verbose_name='联系人')),
                ('contact_method', models.CharField(max_length=255, verbose_name='联系方式')),
                ('advance_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='垫款额度')),
                ('temporary_advance_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='临时垫款额度')),
                ('repayment_cycle', models.IntegerField(verbose_name='回款周期')),
                ('petty_cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='备用金')),
                ('business_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_business', to='tianshu.employee', verbose_name='商务')),
                ('media_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_media', to='tianshu.employee', verbose_name='媒介')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submitted', to='tianshu.employee', verbose_name='提交人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('contract_number', models.CharField(max_length=255, verbose_name='合同编号')),
                ('file_content', models.TextField(verbose_name='文件内容')),
                ('signed_date', models.DateTimeField(verbose_name='签订时间')),
                ('expiration_date', models.DateTimeField(verbose_name='截止时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_customer', to='tianshu.customer', verbose_name='客户')),
                ('business_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_business', to='tianshu.employee', verbose_name='商务')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submitted', to='tianshu.employee', verbose_name='提交人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('approval_content', models.TextField(verbose_name='审批内容')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_approved', to='tianshu.employee', verbose_name='审批人')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_submitted', to='tianshu.employee', verbose_name='提交人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('agent_group', models.CharField(max_length=255, verbose_name='代理商群')),
                ('placement_type', models.CharField(max_length=255, verbose_name='投放类型')),
                ('payment_method', models.CharField(max_length=255, verbose_name='支付方式')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submitted', to='tianshu.employee', verbose_name='提交人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('account_id', models.CharField(db_index=True, max_length=255, verbose_name='账户ID')),
                ('account_name', models.CharField(max_length=255, verbose_name='账户名称')),
                ('customer_group', models.CharField(max_length=255, verbose_name='客户群')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_agent', to='tianshu.agent', verbose_name='代理商')),
                ('media_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_media', to='tianshu.employee', verbose_name='媒介')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submitted', to='tianshu.employee', verbose_name='提交人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformAccountRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='tianshu.account', verbose_name='账户')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges_agent', to='tianshu.agent', verbose_name='代理商')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submitted', to='tianshu.employee', verbose_name='提交人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
