# Generated by Django 5.1.3 on 2024-12-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tianshu', '0002_remove_account_submitter_remove_agent_submitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_agent', to='tianshu.agent', verbose_name='代理商'),
        ),
        migrations.AlterField(
            model_name='account',
            name='media_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_media', to='tianshu.employee', verbose_name='媒介'),
        ),
    ]
